config/routes.rb
Rails.application.routes.draw do
  resources :sejours
  
  devise_for :users
  
  root 'home#index'
  
  get 'about' => 'home#about'

  get 'contact' => 'home#contact'
  
  
end

app/models/sejour.rb
class Sejour < ActiveRecord::Base
  
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sejours
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/sejours_controller.rb
class SejoursController < ApplicationController
  before_action :set_sejour, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /sejours
  # GET /sejours.json
  def index
    @sejours = Sejour.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /sejours/1
  # GET /sejours/1.json
  def show
  end

  # GET /sejours/new
  def new
    @sejour = Sejour.new
  end

  # GET /sejours/1/edit
  def edit
  end

  # POST /sejours
  # POST /sejours.json
  def create
    @sejour = current_user.sejours.build(sejour_params)

    respond_to do |format|
      if @sejour.save
        format.html { redirect_to @sejour, notice: 'Le sejour a bien ete cree.' }
        format.json { render :show, status: :created, location: @sejour }
      else
        format.html { render :new }
        format.json { render json: @sejour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sejours/1
  # PATCH/PUT /sejours/1.json
  def update
    respond_to do |format|
      if @sejour.update(sejour_params)
        format.html { redirect_to @sejour, notice: 'Sejour mis a jour.' }
        format.json { render :show, status: :ok, location: @sejour }
      else
        format.html { render :edit }
        format.json { render json: @sejour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sejours/1
  # DELETE /sejours/1.json
  def destroy
    @sejour.destroy
    respond_to do |format|
      format.html { redirect_to sejours_url, notice: 'Sejour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sejour
      @sejour = Sejour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sejour_params
      params.require(:sejour).permit(:lieu, :description, :note, :recommandation)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sejours_helper.rb
module SejoursHelper
end

app/views/home/about.html.erb
<% provide(:titre, "A propos du site") %>
<div class="jumbotron">
<h1 class="page-header">A propos du site</h1>
<p>site réalisé en Ruby On Rails4 html5 css3 Bootstrap3 </p>
</div> 

app/views/home/contact.html.erb
<% provide(:titre, "Page de contact") %>
<div class="jumbotron">
<h1 class="page-header">Contact</h1>
<p>Retrouvez l'évolution du projet sur <%= link_to 'github', 'https://www.github.com/webyprod' %></p>
</div>

app/views/home/index.html.erb
<% provide(:titre, "Page d'accueil") %>
<div class="jumbotron">
<h1 class="page-header">Bienvenue sur Photo-vacances</h1>
<p>Dans ce site, immortalisez vos vacances en intégrant une de vos photos de vacances.</p>
<p>Vous pourrez ici mettre une note et le partager avec les autres utilisateurs</p>
</div>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar haut">
<div class="container-fluid">
<ul class="nav navbar-nav navbar-left">
   <li><%= link_to 'Home', root_path %></li>
   <li><%= link_to 'A propos', about_path %></li>
   <li><%= link_to 'Contact', contact_path %></li>
</ul>

<ul class="nav navbar-nav navbar-right">
   <li><%= link_to "Liste sejours", sejours_path %></li>
   <% if user_signed_in? %>
      <li><%= link_to "Ajouter un sejour", new_sejour_path %></li>
      <li><%= link_to "Modifier le profil", edit_user_registration_path %></li>
      <li><%= link_to "Deconnexion", destroy_user_session_path, method: :delete %></li>
   <% else %>
      <li><%= link_to "Connexion", new_user_session_path %></li>
   <% end %>
</ul>
</div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:titre) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/sejours/_form.html.erb
<%= form_for(@sejour) do |f| %>
  <% if @sejour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sejour.errors.count, "error") %> prohibited this sejour from being saved:</h2>

      <ul>
      <% @sejour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :lieu %><br>
    <%= f.text_field :lieu, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :note %><br>
    <%= f.number_field :note %>
  </div>
  <div class="form-group">
    <%= f.label :recommandation %><br>
    <%= f.check_box :recommandation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sejours/edit.html.erb
<% provide(:titre, "Modification du sejour") %>
<h1>Modification sejour</h1>

<%= render 'form' %>

<%= link_to 'Visualiser', @sejour %> |
<%= link_to 'Retour', sejours_path %>

app/views/sejours/index.html.erb
<% provide(:titre, "Liste des sejours") %>
<p id="notice"><%= notice %></p>
    <% @sejours.each do |sejour| %>
    <div class="row">
    <div class="col-offset-3 col-sm-7">
    <div class="panel panel-default">
	<div class="panel-heading">
        <%= sejour.lieu %></div>
        <div class="panel-body">
        <table class="table table-striped">
        <tr>
        <td>
        Description :</td><td><%= sejour.description %></td></tr>
        <tr>
        <td>Note :</td><td><%= sejour.note %></td></tr>
        <tr>
        <td>Le recommandez-vous ? </td><td><% if sejour.recommandation == true %>
        Oui
        <% else %>
        Non
        <% end %>
        </td></tr></table>
        </div>
        <div class="panel-footer">
        <%= link_to 'Montrer', sejour %><br>
        <% if sejour.user == current_user %>
        <%= link_to 'Modifier', edit_sejour_path(sejour) %><br>
        <%= link_to 'Supprimer', sejour, method: :delete, data: { confirm: 'Etes vous sûr?' } %>
        <% end %>
        </div>
    </div>
    </div>
    </div>
    <% end %>
    

<br>

<%= will_paginate @sejours, renderer: BootstrapPagination::Rails %>

app/views/sejours/new.html.erb
<% provide(:titre, "Nouveau sejour") %>
<h1>Nouveau Sejour</h1>

<%= render 'form' %>

<%= link_to 'Retour', sejours_path %>

app/views/sejours/show.html.erb
<% provide(:titre, "Visualisation sejour") %>
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-sm-12">
  Ce sejour qui a eu lieu en
  <%= @sejour.lieu %> a obtenu la note de : <%= @sejour.note %>.
    <% if @sejour.recommandation == true %>
  Il recommande fortement ce voyage
  <% else %>
  Il ne recommande pas ce voyage 
  <% end %>
  </div>
  </div>
  <div class="row">
  <div class="col-sm-12">
  <strong>Description:</strong>
  <%= @sejour.description %>
  </div>



<% if @sejour.user == current_user %>
<%= link_to 'Modifier | ', edit_sejour_path(@sejour) %>
<% end %>
<%= link_to 'Retour', sejours_path %>